### ISSUE TITLE
Use allowlist_externals in favor of deprecated whitelist_externals

### ISSUE THREAD

**Issue by reillysiemens** [thedrow/tox-pyo3#2]
Tox permits users to set either [`allowlist_externals`](https://tox.readthedocs.io/en/latest/config.html#conf-allowlist_externals) or `whitelist_externals`. The latter of the two is now deprecated. Unfortunately, Tox does not allow users to set both. Since this plugin sets `whitelist_externals` one is prevented from using `allowlist_externals` in their own configuration.

If possible, I think that it would be ideal to prefer `allowlist_externals` over `whitelist_externals` and would be happy to submit a PR for the change myself. If I understand correctly, however, the caveat is that this plugin would only operate with tox > 3.18.

**Comment by thedrow** [comment]
Thanks for the report. I'd accept a PR to change this.
On a side note, when I wrote this plugin, pyo3-pack didn't automatically compile the code when I ran tox.
I believe maturin should work with tox. See https://github.com/PyO3/maturin/issues/176.

**Comment by reillysiemens** [comment]
Good to know. Thanks. I've submitted a PR which should resolve this. :smile:

**Comment by reillysiemens** [comment]
Thanks again for responding to this so quickly, @thedrow. Any chance of a release with this change?

No rush as I have a workaround using a VCS install, but it would be nice not to depend on that.
```ini
requires =
    tox-pyo3@git+https://github.com/thedrow/tox-pyo3.git@fd4af27a54e5986fa732eb0d265c7c0161855b30
```

**Comment by thedrow** [comment]
I'll try to get to it today.
